routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/dashboard');
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

    Route::group(['prefix' => 'master', 'as' => 'master.'], function () {
        // -- Master Product
        Route::resource('/product', App\Http\Controllers\Master\MasterProductController::class)
            ->only(['index', 'create', 'store', 'edit', 'update']);
        Route::get('/product/{product}/destroy', [App\Http\Controllers\Master\MasterProductController::class, 'destroy'])->name('product.destroy');
    });
});

app/Models/Master/MasterProduct.php
<?php

namespace App\Models\Master;

use App\Traits\Uuid;
use Illuminate\Database\Eloquent\Model;

class MasterProduct extends Model
{
    use Uuid;

    public $incrementing = false;
    protected $keyType = 'uuid';
    protected $table = 'master_products';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'photo',
        'quantity',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use App\Traits\Uuid;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use Uuid, HasApiTokens, HasFactory, Notifiable;

    public $incrementing = false;
    protected $keyType = 'uuid';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use DB;
use Auth;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('dashboard');
    }
}

app/Http/Controllers/File/FileController.php
<?php

namespace App\Http\Controllers\File;

use Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

// Controller
use App\Http\Controllers\Controller;

class FileController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {

    }

    public static function save_image($file, $type)
    {
        $filename = rand(1, 100).time().rand(1, 100).'.'.$file->getClientOriginalExtension();
        $path = 'assets/images/'.$type;

        if (!file_exists($path)) {
            mkdir($path, 666, true);
        }

        $path = $path.'/'.$filename;

        Image::make($file)->save($path);
        return $path;
    }
}

app/Http/Controllers/Master/MasterProductController.php
<?php

namespace App\Http\Controllers\Master;

use Auth;
use Datatables;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

// Controller
use App\Http\Controllers\Controller;
use App\Http\Controllers\File\FileController;

// Models
use App\Models\Master\MasterProduct;

class MasterProductController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {

    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('master.product.index');
    }

    public function create()
    {
        $data['exists'] = 'create';

        return view('master.product.form', $data);
    }

    public function store(Request $request)
    {
        try {
            if($request->file('product-photo') != null){
                $photo = FileController::save_image($request->file('product-photo'), 'product');
                $request->request->add(['photo' => $photo]);
            }

            $data = MasterProduct::create($request->all());

            return redirect(route('master.product.index'))->with('alert', [
                'alert' => 'success',
                'icon' => 'check',
                'title' => 'Berhasil ! ',
                'text' => 'Data berhasil ditambahkan'
            ]);
        } catch (\Exception $e) {
            return redirect()->back()->with('alert', [
                'alert' => 'danger',
                'icon' => 'attention',
                'title' => 'Gagal ! ',
                'text' => $e->getMessage(),
                // 'text' => 'Kesalahan pada sistem',
            ]);
        }
    }

    public function edit($product)
    {
        $product = MasterProduct::find($product);

        $data['exists'] = $product;

        return view('master.product.form', $data);
    }

    public function update(Request $request, $product)
    {
        try {
            if($request->file('product-photo') != null){
                $photo = FileController::save_image($request->file('product-photo'), 'product');
                $request->request->add(['photo' => $photo]);
            }
            
            $data = MasterProduct::find($product);
            $data->fill($request->all())->save();

            return redirect(route('master.product.index'))->with('alert', [
                'alert' => 'success',
                'icon' => 'check',
                'title' => 'Berhasil ! ',
                'text' => 'Data berhasil diubah'
            ]);
        } catch (\Exception $e) {
            return redirect()->back()->with('alert', [
                'alert' => 'danger',
                'icon' => 'attention',
                'title' => 'Gagal ! ',
                'text' => 'Kesalahan pada sistem',
            ]);
        }
    }

    public function destroy($product)
    {
        try {
            $check = MasterProduct::find($product);

            if(!$check) {
                return redirect()->back()->with('alert', [
                    'alert' => 'danger',
                    'icon' => 'attention',
                    'title' => 'Gagal ! ',
                    'text' => 'Data tidak ditemukan atau sudah dihapus'
                ]);
            }

            $check->delete();

            return redirect(route('master.product.index'))->with('alert', [
                'alert' => 'success',
                'icon' => 'check',
                'title' => 'Berhasil ! ',
                'text' => 'Data berhasil dihapus'
            ]);
        } catch (\Exception $e) {
            return redirect()->back()->with('alert', [
                'alert' => 'danger',
                'icon' => 'attention',
                'title' => 'Gagal ! ',
                'text' => 'Kesalahan pada sistem',
            ]);
        }
    }

    public function table(Request $request) {
        $data = MasterProduct::select();

        return Datatables::of($data)
            ->addColumn('action', function($data) {
                return '<center>
                    <a href="'.route("master.product.edit", ['product' => $data->id]).'" class="btn btn-sm btn-warning text-white m-0">Edit</a>
                    <button id="'.route("master.product.destroy", ['product' => $data->id]).'" class="btn btn-sm btn-danger text-white m-0 btn-hapus">Hapus</a>
                </center>';
            })
            ->make(true);
    }
}

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
        <!-- <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-download fa-sm text-white-50"></i> Generate Report
        </a> -->
    </div>

    <!-- Content Row -->
    <div class="row">
        <!-- Total Blog -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Total Data</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">50</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-check fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Total Guru -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Total Data</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">200</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-user fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Total Alumni -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Total Data</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">200</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-user fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Total Karir -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Total Data</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">200</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-user fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Content Row -->

    <div class="row">

        <!-- Area Chart -->
        <div class="col-xl-8 col-lg-7">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Data</h6>
                    <!-- <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                            aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Dropdown Header:</div>
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div> -->
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-area">
                        <table class="table">
                            <thead>
                                <tr>
                                <th scope="col">#</th>
                                <th scope="col">Name</th>
                                <th scope="col">Quantity</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row">1</th>
                                    <td>Product 1</td>
                                    <td>3.000</td>
                                </tr>
                                <tr>
                                    <th scope="row">2</th>
                                    <td>Product 2</td>
                                    <td>3.000</td>
                                </tr>
                                <tr>
                                    <th scope="row">3</th>
                                    <td>Product 3</td>
                                    <td>3.000</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <!-- Pie Chart -->
        <div class="col-xl-4 col-lg-5">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Jenis Kelamin</h6>
                    <!-- <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                            aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Dropdown Header:</div>
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div> -->
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-pie pt-4 pb-2">
                        <canvas id="gender-chart"></canvas>
                    </div>
                    <div class="mt-4 text-center small">
                        <span class="mr-2">
                            <i class="fas fa-circle text-primary"></i> Pria
                        </span>
                        <span class="mr-2">
                            <i class="fas fa-circle text-success"></i> Wanita
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('script')
<script>
    $(document).ready(function() {
        renderChart();
    })

    var renderChart = () => {
        // Set new default font family and font color to mimic Bootstrap's default styling
        Chart.defaults.global.defaultFontFamily = 'Nunito', '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
        Chart.defaults.global.defaultFontColor = '#858796';
    
        // Pie Chart Example
        var ctx = document.getElementById("gender-chart");
        var genderChart = new Chart(ctx, {
            type: 'doughnut',
            data: {
                labels: ["Pria", "Wanita"],
                datasets: [{
                    data: [3, 4],
                    backgroundColor: ['#4e73df', '#1cc88a'],
                    hoverBackgroundColor: ['#2e59d9', '#17a673'],
                    hoverBorderColor: "rgba(234, 236, 244, 1)",
                }],
            },
            options: {
                maintainAspectRatio: false,
                tooltips: {
                    backgroundColor: "rgb(255,255,255)",
                    bodyFontColor: "#858796",
                    borderColor: '#dddfeb',
                    borderWidth: 1,
                    xPadding: 15,
                    yPadding: 15,
                    displayColors: false,
                    caretPadding: 10,
                },
                legend: {
                    display: false
                },
                cutoutPercentage: 80,
            }
        });
    }
</script>
@endpush

resources/views/layouts/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ route('dashboard') }}">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-file"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Page Title</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{{ route('dashboard') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapse-data-master"
            aria-expanded="true" aria-controls="collapse-data-master">
            <i class="fas fa-fw fa-cog"></i>
            <span>Data Master</span>
        </a>
        <div id="collapse-data-master" class="collapse" aria-labelledby="heading-data-master" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Data Master</h6>
                <a class="collapse-item" href="{{ route('master.product.index') }}">Master Data</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <!-- <div class="sidebar-heading">
        Addons
    </div> -->

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>

resources/views/master/product/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Tambah Product</h1>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <!-- Row Form -->
                    <div class="row">
                        <div class="col">
                            <form id="form-action" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="txt-product-photo">Photo</label>
                                            <input type="file" class="form-control" name="product-photo" id="fl-product-photo">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="txt-name">Name</label>
                                            <input type="text" class="form-control" name="name" id="txt-name" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="txt-quantity">Quantity</label>
                                            <input type="number" class="form-control" name="quantity" id="txt-quantity" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="row mt-4">
                                    <div class="col">
                                        <div class="form-group d-flex">
                                            <button class="btn btn-primary ml-auto" type="submit">Simpan</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('script')
    <script>
        var exists = '{{ $exists }}';

        var renderComponents = () => {
            if(exists == 'create') {
                $('#form-action').attr('action', '{{ route("master.product.store") }}')
            }else{
                $('#txt-name').val('{{ $exists != "create" ? $exists->name : "" }}')
                $('#txt-quantity').val('{{ $exists != "create" ? $exists->quantity : "" }}')

                $('#form-action').prepend(`<input type="hidden" name="_method" value="PUT">`)
                $('#form-action').attr('action', '{{ url("master/product") }}/'+'{{ $exists != "create" ? $exists->id : "create" }}')
            }
        }

        $(document).ready(function() {
            renderComponents();
        })
    </script>
@endpush

resources/views/master/product/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Master Product</h1>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <!-- Row Action -->
                    <div class="row mb-3">
                        <div class="col d-flex">
                            <div class="d-flex ml-auto">
                                <a href="{{ route('master.product.create') }}" class="btn btn-primary">+ Tambah</a>
                            </div>
                        </div>
                    </div>

                    <!-- Row Table -->
                    <div class="row">
                        <div class="col">
                            <table id="datatable" class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Photo</th>
                                        <th>Name</th>
                                        <th>Quantity</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('script')
    <script>
        var datatable = null

        var renderDatatable = () => {
            if(datatable) {
                datatable.destroy();
            }

            tableDatatable();
        }

        var tableDatatable = () => {
            datatable = $('#datatable').DataTable({
                scrollX: true,
                pagingType: "full_numbers",
                autoWidth: false,
                order: [],
                language: {
                    emptyTable: 'Tidak ada data yang tersedia',
                    info: 'Menampilkan _START_ sampai _END_ dari _TOTAL_ data',
                    infoEmpty: 'Menampilkan 0 sampai 0 dari 0 data',
                    infoFiltered: '(hasil filter dari _MAX_ total data)',
                    lengthMenu: 'Tampilkan _MENU_ data',
                    loadingRecords: 'Memuat...',
                    processing: 'Sedang Memproses...',
                    search: '',
                    searchPlaceholder: 'Cari..',
                    zeroRecords: 'Tidak ada data yang sesuai',
                    paginate: {
                        first: 'Awal',
                        last: 'Akhir',
                        next: 'Selanjutnya',
                        previous: 'Sebelumnya',
                    },
                },
                ajax: {
                    method: 'POST',
                    url: "{{ url('api/master/product/table') }}",
                    data: function (data) {
                        //
                    }
                },
                columns: [
                    {
                        data: null,
                        orderable: false,
                        searchable: false
                    },
                    {
                        data: 'photo',
                        name: 'photo',
                        orderable: false,
                        render: function (data, type, full, meta) {
                            data = data ? data : null
                            return `<img class="img-fluid" src="{{ asset('') }}${data}">`
                        }
                    },
                    {
                        data: 'name',
                        name: 'name',
                        orderable: false,
                        render: function (data, type, full, meta) {
                            data = data ? data : null
                            return data
                        }
                    },
                    {
                        data: 'quantity',
                        name: 'quantity',
                        orderable: false,
                        render: function (data, type, full, meta) {
                            data = data ? data : null
                            return data
                        }
                    },
                    {
                        data: 'action',
                        orderable: false,
                        searchable: false
                    }
                ],
                dom: 'lfrtip',
                "rowCallback": function(nRow, aData, iDisplayIndex) {
                    var oSettings = this.fnSettings();
                    $("td:first", nRow).html(oSettings._iDisplayStart + iDisplayIndex + 1);
                    return nRow;
                }
            });
        }

        var eventHandler = () => {
            $('table').on('click', '.btn-hapus', function(e) {
                Swal.fire({
                    title: 'Hapus Data ini?',
                    text: "Data yang dihapus tidak dapat dikembalikan!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#6c757d',
                    confirmButtonText: 'Batal',
                    cancelButtonColor: '#dc3545',
                    cancelButtonText: 'Hapus'
                }).then((result) => {
                    if (!result.value) {
                        window.location.href = $(this).attr('id')
                    }
                })
            })
        }

        var deleteData = () => {

        }

        $(document).ready(function() {
            renderDatatable();
            eventHandler();
        })
    </script>
@endpush